apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - path: vote-deployment-patch.yaml
  - path: result-deployment-patch.yaml
  - path: worker-deployment-patch.yaml
  - path: db-statefulset-patch.yaml
  - path: vote-ingress-patch.yaml
  - path: result-ingress-patch.yaml